/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Legacy */

#ifndef _Included_Legacy
#define _Included_Legacy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Legacy
 * Method:    countPrimes
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Legacy_countPrimes
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Legacy
 * Method:    selectPrimes
 * Signature: (JIZ)[J
 */
JNIEXPORT jlongArray JNICALL Java_Legacy_selectPrimes
  (JNIEnv *, jclass, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
